
services:

  postgres:
    image: postgres:15
    container_name: hotel-reservation-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - hotel-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - hotel-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - hotel-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - reservation-service
      - hotel-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "9080:8080"
    networks:
      - hotel-network

  reservation-service:
    build: ./reservation-service
    container_name: reservation-service
    depends_on:
      - postgres
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "9082:8082"
    networks:
      - hotel-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    depends_on:
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "9083:8083"
    networks:
      - hotel-network

  hotel-service:
    build: ./hotel-service
    container_name: hotel-service
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "9081:8081"
    networks:
      - hotel-network

volumes:
  pgdata:

networks:
  hotel-network:
    driver: bridge
