server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - AddResponseHeader=X-Gateway, HOTEL API GATEWAY, HOTEL API GATEWAY


services:
  hotel: http://hotel-service:8081
  reservation: http://reservation-service:8082
