server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/reservation_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: kafka:9092

  application:
    name: reservation-service


services:
  hotel: http://hotel-service:8081