server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/hotel_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always


  application:
    name: hotel-service